, "CALLE", "PASEO", "PLAZA", "GLORIETA", "RONDA", "CAMINO", "PISTA", "ANILLO", "CRUCE", "AUTOVIA", "CARRETERA", "PARQUE", "CUESTA", "CAÑADA", "AVENIDA", "BULEVAR", "JARDIN", "PARTICULAR", "POLIGONO", "GALERIA", "ESCALINATA", "VIA", "PASARELA", "PASAJE", "PUENTE", "COSTANILLA", "COLONIA", "CARRERA", "PLAZUELA", "ACCESO", "POBLADO", "PASADIZO", "TRASERA", "SENDA", "ARROYO", "VALLE", "AEROPUERTO", "PASO_ELEVADO", "SENDA_CICLABLE", "PASAJE", 




"GALERIA"

"CAÑADA"

"AUTOPISTA"

"POLIGONO"

"RONDA"

"AEROPUERTO"

"PUENTE"

"TRAVESIA"

"PLAZUELA"

"CALLEJON"

"COSTANILLA"

"JARDIN"

"ARROYO"

"PARTICULAR"

"TRASERA"

"COLONIA"
